#
<<<<<<< Updated upstream
<<<<<<< HEAD
#Sun May 24 23:45:39 COT 2026
=======
#Mon May 25 14:08:28 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --test-type, --no-sandbox, --ignore-certificate-errors, \\n                   --disable-popup-blocking, --disable-default-apps, --disable-extensions-file-access-check, \\n                   --disable-infobars,--disable-gpu, --remote-allow-origins\=*], extensions\=[]}
>>>>>>> da76a1b5d9b16fb29d34c33ee9cbb1c4ed736eed
=======
#Mon May 25 15:57:36 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --test-type, --no-sandbox, --ignore-certificate-errors, \\r\\n                   --disable-popup-blocking, --disable-default-apps, --disable-extensions-file-access-check, \\r\\n                   --disable-infobars,--disable-gpu, --remote-allow-origins\=*], extensions\=[]}
>>>>>>> Stashed changes
acceptInsecureCerts=true
browserName=chrome
